import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Heart,UserRound,LogOut,Send} from 'lucide-react';
import {supabase} from './supabase';
import {genres,movies} from './data/movies';

export function useAccount(){
 const [user,setUser]=useState(null);
 useEffect(()=>{if(!supabase)return;supabase.auth.getUser().then(({data})=>setUser(data.user||null));const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user||null));return()=>subscription.unsubscribe()},[]);
 return user;
}
export function FavoriteButton({movieId,user}){
 const [saved,setSaved]=useState(false),[busy,setBusy]=useState(false);
 const navigate=useNavigate();
 useEffect(()=>{let active=true;setSaved(false);if(user&&supabase)supabase.from('favorites').select('movie_id').eq('user_id',user.id).eq('movie_id',movieId).maybeSingle().then(({data})=>{if(active)setSaved(!!data)});return()=>{active=false}},[user?.id,movieId]);
 async function toggle(){if(!user){navigate('/entrar');return}if(!supabase)return;setBusy(true);const result=saved?await supabase.from('favorites').delete().eq('user_id',user.id).eq('movie_id',movieId):await supabase.from('favorites').insert({user_id:user.id,movie_id:movieId});if(result.error)alert(result.error.message);else setSaved(!saved);setBusy(false)}
 return <button type="button" disabled={busy} className={'favorite-button '+(saved?'is-favorite':'')} onClick={toggle}><Heart size={18} fill={saved?'currentColor':'none'}/>{saved?'Remover dos favoritos':'Adicionar aos favoritos'}</button>
}
export function Login(){const [register,setRegister]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[username,setUsername]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const navigate=useNavigate();
 async function submit(e){e.preventDefault();if(!supabase){setMessage('Configure o Supabase antes de usar o login.');return}setBusy(true);setMessage('');const {data,error}=register?await supabase.auth.signUp({email,password,options:{data:{username}}}):await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error){setMessage(error.message);return}if(register&&!data.session)setMessage('Cadastro realizado! Confira seu e-mail para confirmar a conta.');else navigate('/perfil')}
 return <main className="community-page"><section className="community-panel"><span className="eyebrow">SUA CONTA M&M</span><h1>{register?'Criar minha conta':'Entrar'}</h1><p>Salve seus filmes favoritos e personalize seu perfil.</p><form onSubmit={submit}>{register&&<label>Nome de usuário<input required minLength="2" maxLength="40" value={username} onChange={e=>setUsername(e.target.value)} placeholder="Como quer ser chamado(a)"/></label>}<label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Senha<input type="password" required minLength="6" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={register?'new-password':'current-password'}/></label><button className="primary" disabled={busy}>{busy?'Aguarde...':register?'Criar conta':'Entrar'}</button></form>{message&&<p role="status">{message}</p>}<button className="text-button" onClick={()=>{setRegister(!register);setMessage('')}}>{register?'Já tem conta? Entrar':'Não tem conta? Cadastre-se'}</button></section></main>
}
export function Profile({user}){const navigate=useNavigate();const [profile,setProfile]=useState({username:'',avatar_url:'',favorite_genres:[]}),[favoriteIds,setFavoriteIds]=useState([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!user||!supabase)return;supabase.from('profiles').select('username,avatar_url,favorite_genres').eq('id',user.id).maybeSingle().then(({data})=>{if(data)setProfile({username:data.username||'',avatar_url:data.avatar_url||'',favorite_genres:data.favorite_genres||[]})});supabase.from('favorites').select('movie_id').eq('user_id',user.id).then(({data})=>setFavoriteIds((data||[]).map(x=>x.movie_id)))},[user?.id]);
 if(!user)return <main className="community-page"><section className="community-panel"><h1>Seu perfil</h1><p>Entre na sua conta para ver seus favoritos.</p><Link className="primary" to="/entrar">Entrar</Link></section></main>;
 async function save(e){e.preventDefault();setBusy(true);const {error}=await supabase.from('profiles').upsert({id:user.id,username:profile.username,avatar_url:profile.avatar_url,favorite_genres:profile.favorite_genres});setMessage(error?error.message:'Perfil atualizado!');setBusy(false)}
 async function upload(e){const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>2*1024*1024){setMessage('Escolha uma imagem de até 2 MB.');return}setBusy(true);const ext=file.name.split('.').pop().toLowerCase();const path=user.id+'/avatar-'+Date.now()+'.'+ext;const {error}=await supabase.storage.from('avatars').upload(path,file,{contentType:file.type});if(error)setMessage(error.message);else{const {data}=supabase.storage.from('avatars').getPublicUrl(path);setProfile(p=>({...p,avatar_url:data.publicUrl}));setMessage('Foto enviada! Clique em Salvar perfil para confirmar.')}setBusy(false)}
 return <main className="community-page profile-page"><section className="community-panel"><span className="eyebrow">MEU ESPAÇO</span><h1><UserRound/> Meu perfil</h1>{profile.avatar_url&&<img className="avatar" src={profile.avatar_url} alt="Foto de perfil"/>}<form onSubmit={save}><label>Foto de perfil<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label><label>Nome de usuário<input required maxLength="40" value={profile.username} onChange={e=>setProfile(p=>({...p,username:e.target.value}))}/></label><label>E-mail<input disabled value={user.email||''}/></label><p>Gêneros que você gosta</p><div className="genre-picks">{genres.filter(g=>g!=='Todos').map(g=><label key={g}><input type="checkbox" checked={profile.favorite_genres.includes(g)} onChange={e=>setProfile(p=>({...p,favorite_genres:e.target.checked?[...p.favorite_genres,g]:p.favorite_genres.filter(x=>x!==g)}))}/>{g}</label>)}</div><button className="primary" disabled={busy}>Salvar perfil</button></form>{message&&<p role="status">{message}</p>}<button className="text-button" onClick={async()=>{await supabase.auth.signOut();navigate('/')}}><LogOut size={16}/> Sair da conta</button></section><section className="community-panel"><h2><Heart/> Meus filmes favoritos</h2><div className="favorites-grid">{movies.filter(m=>favoriteIds.includes(m.id)).map(m=><Link to={'/filme/'+m.id} key={m.id}>{m.poster&&<img src={m.poster} alt=""/>}<strong>{m.title}</strong></Link>)}</div>{!favoriteIds.length&&<p>Você ainda não adicionou nenhum filme aos favoritos.</p>}</section></main>
}
export function RequestMovie({user}){const [title,setTitle]=useState(''),[year,setYear]=useState(''),[note,setNote]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setBusy(true);setMessage('');if(!supabase){setMessage('O serviço de pedidos ainda não foi configurado.');setBusy(false);return}const {error}=await supabase.from('movie_requests').insert({title:title.trim(),release_year:year?Number(year):null,note:note.trim()||null,user_id:user?.id||null});setBusy(false);if(error)setMessage('Não foi possível enviar o pedido: '+error.message);else{setMessage('Pedido recebido! Obrigado pela sugestão.');setTitle('');setYear('');setNote('')}}
 return <main className="community-page"><section className="community-panel"><span className="eyebrow">SUGESTÕES DO PÚBLICO</span><h1><Send/> Pedir um filme</h1><p>Não encontrou o filme que queria? Conte para nós! Seu pedido será registrado para análise.</p><form onSubmit={submit}><label>Nome do filme<input required maxLength="150" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Qual filme você quer ver aqui?"/></label><label>Ano (opcional)<input type="number" min="1888" max="2100" value={year} onChange={e=>setYear(e.target.value)}/></label><label>Observações (opcional)<textarea maxLength="500" rows="4" value={note} onChange={e=>setNote(e.target.value)} placeholder="Conte algum detalhe para identificarmos o filme"/></label><button className="primary" disabled={busy}>{busy?'Enviando...':'Enviar pedido'}</button></form>{message&&<p role="status">{message}</p>}<small>O envio registra o pedido no sistema. Notificações por e-mail precisam ser ativadas separadamente.</small></section></main>
}
